# Register list for the Wago Energy Meter
REGISTERS = {
    "Protocol version": {
        "address": "4005",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "Software Version": {
        "address": "4007",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "Hardware version": {
        "address": "4009",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "S0 pulse rate": {
        "address": "400D",
        "count": 2,
        "type": "float32",
        "unit": "pulse/kWh",
    },
    "Voltage*": {
        "address": "5000",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "L1 voltage": {
        "address": "5002",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "L2 voltage": {
        "address": "5004",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "L3 voltage": {
        "address": "5006",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "Frequency": {
        "address": "5008",
        "count": 2,
        "type": "float32",
        "unit": "Hz",
    },
    "Current*": {
        "address": "500A",
        "count": 2,
        "type": "float32",
        "unit": "A",
    },
    "L1 current": {
        "address": "500C",
        "count": 2,
        "type": "float32",
        "unit": "A",
    },
    "L2 current": {
        "address": "500E",
        "count": 2,
        "type": "float32",
        "unit": "A",
    },
    "L3 current": {
        "address": "5010",
        "count": 2,
        "type": "float32",
        "unit": "A",
    },
    "Total active power": {
        "address": "5012",
        "count": 2,
        "type": "float32",
        "unit": "kW",
    },
    "L1 active power": {
        "address": "5014",
        "count": 2,
        "type": "float32",
        "unit": "kW",
    },
    "L2 active power": {
        "address": "5016",
        "count": 2,
        "type": "float32",
        "unit": "kW",
    },
    "L3 active power": {
        "address": "5018",
        "count": 2,
        "type": "float32",
        "unit": "kW",
    },
    "Total reactive power": {
        "address": "501A",
        "count": 2,
        "type": "float32",
        "unit": "kvar",
    },
    "L1 reactive power": {
        "address": "501C",
        "count": 2,
        "type": "float32",
        "unit": "kvar",
    },
    "L2 reactive power": {
        "address": "501E",
        "count": 2,
        "type": "float32",
        "unit": "kvar",
    },
    "L3 reactive power": {
        "address": "5020",
        "count": 2,
        "type": "float32",
        "unit": "kvar",
    },
    "Total apparent power": {
        "address": "5022",
        "count": 2,
        "type": "float32",
        "unit": "kVA",
    },
    "L1 apparent power": {
        "address": "5024",
        "count": 2,
        "type": "float32",
        "unit": "kVA",
    },
    "L2 apparent power": {
        "address": "5026",
        "count": 2,
        "type": "float32",
        "unit": "kVA",
    },
    "L3 apparent power": {
        "address": "5028",
        "count": 2,
        "type": "float32",
        "unit": "kVA",
    },
    "Power factor": {
        "address": "502A",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "L1 power factor": {
        "address": "502C",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "L2 power factor": {
        "address": "502E",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "L3 power factor": {
        "address": "5030",
        "count": 2,
        "type": "float32",
        "unit": "-",
    },
    "L1-L2 voltage": {
        "address": "5032",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "L1-L3 voltage": {
        "address": "5034",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "L2-L3 voltage": {
        "address": "5036",
        "count": 2,
        "type": "float32",
        "unit": "V",
    },
    "Total active energy": {
        "address": "6000",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T1 Total active energy": {
        "address": "6002",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T2 Total active energy": {
        "address": "6004",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L1 Total active energy": {
        "address": "6006",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L2 Total active energy": {
        "address": "6008",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L3 Total active energy": {
        "address": "600A",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "Active energy import": {
        "address": "600C",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T1 Active energy import": {
        "address": "600E",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T2 Active energy import": {
        "address": "6010",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L1 Active energy import": {
        "address": "6012",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L2 Active energy import": {
        "address": "6014",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L3 Active energy import": {
        "address": "6016",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "Active energy export": {
        "address": "6018",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T1 Active energy export": {
        "address": "601A",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T2 Active energy export": {
        "address": "601C",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L1 Active energy export": {
        "address": "601E",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L2 Active energy export": {
        "address": "6020",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "L3 Active energy export": {
        "address": "6022",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "Total reactive energy": {
        "address": "6024",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T1 Total reactive energy": {
        "address": "6026",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T2 Total reactive energy": {
        "address": "6028",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L1 Total reactive energy": {
        "address": "602A",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L2 Total reactive energy": {
        "address": "602C",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L3 Total reactive energy": {
        "address": "602E",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "Reactive energy import": {
        "address": "6030",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T1 Reactive energy import": {
        "address": "6032",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T2 Reactive energy import": {
        "address": "6034",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L1 Reactive energy import": {
        "address": "6036",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L2 Reactive energy import": {
        "address": "6038",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L3 Reactive energy import": {
        "address": "603A",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "Reactive energy export": {
        "address": "603C",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T1 Reactive energy export": {
        "address": "603E",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T2 Reactive energy export": {
        "address": "6040",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L1 Reactive energy export": {
        "address": "6042",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L2 Reactive energy export": {
        "address": "6044",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "L3 Reactive energy export": {
        "address": "6046",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "Resettable day register": {
        "address": "6049",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T3 Total active energy": {
        "address": "604B",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T4 Total active energy": {
        "address": "604D",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T3 Import active energy": {
        "address": "604F",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T4 Import active energy": {
        "address": "6051",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T3 Export active energy": {
        "address": "6053",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T4 Export active energy": {
        "address": "6055",
        "count": 2,
        "type": "float32",
        "unit": "kWh",
    },
    "T3 Total reactive energy": {
        "address": "6057",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T4 Total reactive energy": {
        "address": "6059",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T3 Import reactive energy": {
        "address": "605B",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T4 Import reactive energy": {
        "address": "605D",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T3 Export reactive energy": {
        "address": "605F",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "T4 Export reactive energy": {
        "address": "6061",
        "count": 2,
        "type": "float32",
        "unit": "kvarh",
    },
    "Modbus ID": {
        "address": "4003",
        "count": 1,
        "type": "signed",
        "unit": "-",
    },
    "Baud rate": {
        "address": "4004",
        "count": 1,
        "type": "signed",
        "unit": "-",
    },
    "Parity": {
        "address": "4011",
        "count": 1,
        "type": "signed",
        "unit": "-",
    },
    "L1 quadrant": {
        "address": "4018",
        "count": 1,
        "type": "signed",
        "unit": "-",
    },
}
